Repository code-syncers/quiz-shower, pull requests merged in 2023-10, with the labels that each got.

#22 ci: add pr write permission labelWhenApproved
  .github/workflows/label-approved-pull-requests.yml
Labels: approved

#31 fix: cocoabods, podをインストール
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
Labels: bug, approved

#35 feat: NavigationDrawerの実装
  lib/quiz_shower_app.dart
  lib/ui/screen/setting_screen/setting_screen.dart
  lib/ui/widget/quiz_shower_scaffold.dart
Labels: approved

#40 chore: setup custom lint rules
  analysis_options.yaml
  lib/main.dart
  lib/quiz_shower_app.dart
  lib/ui/widget/quiz_shower_scaffold.dart
Labels: approved

#37 feat: ログイン機能の搭載
  lib/ui/widget/quiz_shower_scaffold.dart
  pubspec.lock
  pubspec.yaml
  test/mock.dart
  test/widget_test.dart
Labels: ui, firebase, approved

#42 feat: edge-to-edge対応
  lib/quiz_shower_app.dart
Labels: approved

#43 feat: 記事モードとクイズモードの切り替え機能
  Makefile
  lib/data/model/article.dart
  lib/data/model/article.freezed.dart
  lib/quiz_shower_app.dart
  lib/ui/screen/article_screen/article_screen.dart
  lib/ui/screen/home_screen/component/preview_card.dart
  lib/ui/screen/home_screen/home_screen.dart
  lib/ui/screen/home_screen/hook/use_home_screen_state.dart
  lib/ui/screen/home_screen/hook/use_home_screen_state.freezed.dart
  lib/ui/screen/quiz_screen/quiz_screen.dart
  lib/ui/screen/user_screen/user_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: approved

#45 Komugi/issue44
  .vscode/settings.json
  lib/data/model/article.dart
  lib/data/model/article.freezed.dart
  lib/data/model/history.dart
  lib/data/model/history.freezed.dart
  lib/data/model/history_quiz.dart
  lib/data/model/history_quiz.freezed.dart
  lib/data/model/quiz.dart
  lib/data/model/quiz.freezed.dart
  lib/data/model/user.dart
  lib/data/model/user.freezed.dart
  lib/ui/screen/home_screen/component/preview_card.dart
Labels: approved

#48 fix: 新規登録完了時にトップページに遷移
  lib/ui/screen/home_screen/home_screen.dart
Labels: bug, ui, firebase, approved

#50 feat: 設定画面の作成
  ios/Podfile.lock
  lib/quiz_shower_app.dart
  lib/ui/screen/setting_screen/add_auth_screen.dart
  lib/ui/screen/setting_screen/change_email_screen.dart
  lib/ui/screen/setting_screen/setting_screen.dart
Labels: approved

#52 feat: ダッシュボード画面の作成
  lib/ui/screen/dashboard_screen.dart
  lib/ui/screen/home_screen/home_screen.dart
Labels: ui, approved

#59 クイズ画面に問題文と答えを表示
  lib/ui/screen/quiz_screen/hook/use_quiz_screen_state.dart
  lib/ui/screen/quiz_screen/hook/use_quiz_screen_state.freezed.dart
  lib/ui/screen/quiz_screen/quiz_result_screen.dart
  lib/ui/screen/quiz_screen/quiz_screen.dart
Labels: ui, approved

#60 feat: 記事追加画面の作成
  lib/ui/screen/home_screen/add_article_screen.dart
  lib/ui/screen/home_screen/home_screen.dart
Labels: ui, approved

#63 fix: 不要なインタラクティブ要素をグレーアウト
  lib/ui/screen/quiz_screen/quiz_screen.dart
Labels: bug, ui, approved

#64 feat: アプリを共有画面の作成
  assets/images/quiz_shower.png
  lib/ui/screen/home_screen/component/quiz_shower_elevated_button.dart
  lib/ui/screen/home_screen/home_screen.dart
  lib/ui/screen/home_screen/share_app_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: ui, approved

#62 feat: 記事画面の作成
  lib/data/model/article.dart
  lib/quiz_shower_app.dart
  lib/ui/screen/debug_mode/debug_screen.dart
  lib/ui/screen/home_screen/article_screen.dart
  lib/ui/screen/home_screen/home_screen.dart
Labels: ui, approved

#68 firestore: 各データのやり取り
  lib/data/model/article.dart
  lib/data/model/article.freezed.dart
  lib/data/model/article.g.dart
  lib/data/model/firestore_datetime_convert.dart
  lib/data/model/history.dart
  lib/data/model/history.freezed.dart
  lib/data/model/history.g.dart
  lib/data/model/history_quiz.dart
  lib/data/model/history_quiz.freezed.dart
  lib/data/model/history_quiz.g.dart
  lib/data/model/quiz.dart
  lib/data/model/quiz.freezed.dart
  lib/data/model/quiz.g.dart
  lib/data/model/user.dart
  lib/data/model/user.freezed.dart
  lib/data/model/user.g.dart
  lib/data/repository/article_repository.dart
  lib/data/repository/article_repository_impl.dart
  lib/data/repository/di/article_repository_provider.dart
  lib/data/repository/di/article_repository_provider.g.dart
  lib/data/repository/di/history_quiz_repository_provider.dart
  lib/data/repository/di/history_quiz_repository_provider.g.dart
  lib/data/repository/di/history_repository_provider.dart
  lib/data/repository/di/history_repository_provider.g.dart
  lib/data/repository/di/quiz_repository_provider.dart
  lib/data/repository/di/quiz_repository_provider.g.dart
  lib/data/repository/di/user_repository_provider.dart
  lib/data/repository/di/user_repository_provider.g.dart
  lib/data/repository/history_quiz_repository.dart
  lib/data/repository/history_quiz_repository_impl.dart
  lib/data/repository/history_repository.dart
  lib/data/repository/history_repository_impl.dart
  lib/data/repository/quiz_repository.dart
  lib/data/repository/quiz_repository_impl.dart
  lib/data/repository/user_repository.dart
  lib/data/repository/user_repository_impl.dart
  lib/ui/screen/home_screen/component/preview_card.dart
  pubspec.lock
  pubspec.yaml
Labels: priority: important, firebase, approved

#66 feat(functions): generate quizzes when article created
  functions/.eslintrc.js
  functions/.gitignore
  functions/package.json
  functions/pnpm-lock.yaml
  functions/src/convertToMarkdown.ts
  functions/src/createArticleQuiz.ts
  functions/src/createArticleQuizzes.ts
  functions/src/createChatCompletion.ts
  functions/src/debugCreateQuiz.ts
  functions/src/index.ts
  functions/src/onArticleCreated.ts
  functions/src/types/article.ts
  functions/src/types/quiz.ts
  functions/src/types/types.ts
  functions/tsconfig.json
Labels: firebase, approved

#65 クイズ結果画面の作成
  lib/ui/screen/debug_mode/debug_screen.dart
  lib/ui/screen/home_screen/home_screen.dart
  lib/ui/screen/quiz_screen/component/result_character.dart
  lib/ui/screen/quiz_screen/quiz_result_screen.dart
Labels: ui, priority: important, approved

#69 feat: 記事追加画面にURL入力フィールドの追加とfirestoreへのデータ渡し
  lib/main.dart
  lib/ui/screen/home_screen/add_article_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: ui, firebase, approved

#71 feat: homeの実装
  lib/ui/screen/home_screen/component/suggestion.dart
  lib/ui/screen/home_screen/home_screen.dart
  lib/ui/screen/home_screen/hook/use_home_screen_state.dart
  lib/ui/screen/home_screen/hook/use_home_screen_state.freezed.dart
Labels: approved

#72 feat: quiz_screenとfirestoreの連携
  lib/data/model/quiz.dart
  lib/data/model/quiz.freezed.dart
  lib/data/model/quiz.g.dart
  lib/ui/screen/debug_mode/debug_screen.dart
  lib/ui/screen/home_screen/add_article_screen.dart
  lib/ui/screen/home_screen/component/preview_card.dart
  lib/ui/screen/quiz_screen/quiz_result_screen.dart
  lib/ui/screen/quiz_screen/quiz_screen.dart
Labels: firebase

#73 feat: implement article list in home screen
  lib/ui/screen/home_screen/add_article_screen.dart
  lib/ui/screen/home_screen/component/article_list.dart
  lib/ui/screen/home_screen/home_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: approved
